### ISSUE TITLE
change default for ask users

### ISSUE THREAD

**Issue by jdtuck** [david-cortes/findblas#3]
On CI systems using cibuildwheel, depending on the system it will find the blas using the last resort (regex) method and the default is to ask the user. This will fail on CI systems as no input is given. Can we change the default behavior here? Any other thoughts?

**Comment by david-cortes** [comment]
Thanks for the suggestion. I've now added a parameter to make this prompt optional.

By the way, if you are using this library to add BLAS linkage to a python package, and you do not use any function that is specific to a particular BLAS implementation, you might consider making the SciPy BLAS function accessible to C/C++ code by manually adding cython public cdef'd functions mimicing standard BLAS functions so that then all the linkage and symbol lookup would be handled by SciPy.

Here's an example:
https://github.com/david-cortes/cmfrec/blob/2d4d67126588b838e1f9d859e59d2f9d2d459258/cmfrec/cython_cblas.pxi#L79
